---
- name: Provision Slave
  hosts: all
  tasks:
    - name: Copy script for setting up LAMP/Laravel application into the slave VM
      copy:
        src: setup_laravel_lamp.sh
        dest: /tmp/setup_laravel_lamp.sh
        mode: 0755
    
    - name: Executing script for setting up LAMP/Laravel application on the slave VM [This may take a while]
      command: /tmp/setup_laravel_lamp.sh

    - name: Cron job to check server's uptime at 12AM daily
      cron:
        name: check_uptime
        minute: "0"
        hour: "0"
        job: "uptime >> /var/log/uptime.log"
